//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board
{


    public partial class CreateGroup
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        protected global::System.Web.UI.WebControls.Label lblMessage;
        
        protected global::System.Web.UI.UpdatePanel upGroupName;
        
        protected global::System.Web.UI.WebControls.TextBox txtGroupName;
        
        protected global::System.Web.UI.WebControls.Label lblNameStatus;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlTechDomain;
        
        protected global::System.Web.UI.WebControls.LinkButton btnCreateGroup;
    }
}
