//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board
{


    public partial class SignUp
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// fullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox fullName;

        /// <summary>
        /// loginId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox loginId;

        /// <summary>
        /// enrollment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox enrollment;

        /// <summary>
        /// password control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox password;

        /// <summary>
        /// confirmPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox confirmPassword;

        /// <summary>
        /// loginBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton loginBtn;
    }
}
