//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board
{


    public partial class SignUp
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// pnlSignupForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlSignupForm;

        /// <summary>
        /// fullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox fullName;

        /// <summary>
        /// lblFullNameError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFullNameError;

        /// <summary>
        /// loginId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox loginId;

        /// <summary>
        /// lblEmailError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmailError;

        /// <summary>
        /// enrollment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox enrollment;

        /// <summary>
        /// lblEnrollmentError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEnrollmentError;

        /// <summary>
        /// password control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox password;

        /// <summary>
        /// lblPasswordError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPasswordError;

        /// <summary>
        /// confirmPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox confirmPassword;

        /// <summary>
        /// lblConfirmPasswordError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblConfirmPasswordError;

        /// <summary>
        /// loginBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton loginBtn;

        /// <summary>
        /// pnlVerifyCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlVerifyCode;

        /// <summary>
        /// litVerifyEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litVerifyEmail;

        /// <summary>
        /// txtVerifyCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtVerifyCode;

        /// <summary>
        /// lblCodeError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCodeError;

        /// <summary>
        /// btnVerifyAndRegister control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnVerifyAndRegister;

        /// <summary>
        /// btnResendOtp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnResendOtp;

        /// <summary>
        /// btnBackToSignup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnBackToSignup;
    }
}
