//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.Student.Member
{
    public partial class Member_TaskManagement
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Repeater rptMemberTasks;
        protected global::System.Web.UI.WebControls.Label lblNoTasks;
        protected global::System.Web.UI.WebControls.HiddenField hfReportTaskId;
        protected global::System.Web.UI.WebControls.Label lblModalTaskTitle;
        protected global::System.Web.UI.WebControls.Label lblModalLeaderName;
        protected global::System.Web.UI.WebControls.DropDownList ddlUpdateStatus;
        protected global::System.Web.UI.WebControls.TextBox txtMemberReportText;
        protected global::System.Web.UI.WebControls.Button btnSubmitReport;
    }
}
