//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.Student.Member
{
    public partial class Member_Team
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlUnassigned;
        protected global::System.Web.UI.WebControls.Panel pnlAssigned;
        protected global::System.Web.UI.WebControls.Repeater rptRoster;
        protected global::System.Web.UI.WebControls.Panel pnlMentorAssigned;
        protected global::System.Web.UI.WebControls.Panel pnlMentorPending;
        protected global::System.Web.UI.WebControls.Panel pnlMentorNone;
    }
}
