//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.Student.Member
{
    public partial class Member_TaskManagement
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Repeater rptMemberTasks;
        protected global::System.Web.UI.WebControls.Label lblNoTasks;
        protected global::System.Web.UI.WebControls.Repeater rptGroupMentorTasks;
        protected global::System.Web.UI.WebControls.Label lblNoGroupMentorTasks;
    }
}
