//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.Student.Member
{
    public partial class Member_Project
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlNoProject;
        protected global::System.Web.UI.WebControls.Panel pnlProjectDetails;
        protected global::System.Web.UI.WebControls.Label lblGroupName;
        protected global::System.Web.UI.WebControls.Repeater rptMemberProposals;
    }
}
