//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.Student
{
    public partial class Appeal
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.LinkButton btnBack;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Label lblTaskTitle;
        protected global::System.Web.UI.WebControls.Label lblAssignorName;
        protected global::System.Web.UI.WebControls.Label lblFeedback;
        protected global::System.Web.UI.WebControls.TextBox txtReason;
        protected global::System.Web.UI.WebControls.TextBox txtChangesMade;
        protected global::System.Web.UI.WebControls.TextBox txtExplanation;
        protected global::System.Web.UI.WebControls.CheckBox chkIsCompleted;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
