//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.Student.Leader
{
    public partial class Leader_Project
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlWarning;
        protected global::System.Web.UI.WebControls.Panel pnlSubmissionForm;
        protected global::System.Web.UI.WebControls.Label lblWarningMessage;
        protected global::System.Web.UI.WebControls.TextBox txtProjectTitle;
        protected global::System.Web.UI.WebControls.TextBox txtKeywords;
        protected global::System.Web.UI.WebControls.DropDownList ddlProjectType;
        protected global::System.Web.UI.WebControls.TextBox txtFunctionality;
        protected global::System.Web.UI.WebControls.Button btnSubmitProject;
        protected global::System.Web.UI.WebControls.Repeater rptProposals;
    }
}
