//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.Student.Leader
{
    public partial class Leader_TaskManagement
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Repeater rptMentorTasks;
        protected global::System.Web.UI.WebControls.Label lblNoMentorTasks;
        protected global::System.Web.UI.WebControls.DropDownList ddlMembers;
        protected global::System.Web.UI.WebControls.TextBox txtMemberTaskTitle;
        protected global::System.Web.UI.WebControls.DropDownList ddlTaskCategory;
        protected global::System.Web.UI.WebControls.TextBox txtMemberTaskDueDate;
        protected global::System.Web.UI.WebControls.TextBox txtMemberTaskDescription;
        protected global::System.Web.UI.WebControls.Button btnAssignMemberTask;
        protected global::System.Web.UI.WebControls.Repeater rptMemberTasks;
        protected global::System.Web.UI.WebControls.Label lblNoMemberTasks;
        protected global::System.Web.UI.WebControls.DropDownList ddlParentTask;
        protected global::System.Web.UI.WebControls.CheckBox chkMentorColTaskTitle;
        protected global::System.Web.UI.WebControls.CheckBox chkMentorColDescription;
        protected global::System.Web.UI.WebControls.CheckBox chkMentorColAssignedBy;
        protected global::System.Web.UI.WebControls.CheckBox chkMentorColDueDate;
        protected global::System.Web.UI.WebControls.CheckBox chkMentorColStatus;
        protected global::System.Web.UI.WebControls.CheckBox chkMemberColTaskTitle;
        protected global::System.Web.UI.WebControls.CheckBox chkMemberColDescription;
        protected global::System.Web.UI.WebControls.CheckBox chkMemberColAssignedTo;
        protected global::System.Web.UI.WebControls.CheckBox chkMemberColDueDate;
        protected global::System.Web.UI.WebControls.CheckBox chkMemberColStatus;

    }
}
