//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.Admin
{


    public partial class Admin_DeletedRecords
    {

        /// <summary>
        /// ddlTypeFilter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlTypeFilter;

        /// <summary>
        /// txtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>
        /// txtDateFrom control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDateFrom;

        /// <summary>
        /// txtDateTo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDateTo;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// btnClear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClear;

        /// <summary>
        /// lblTotalDeleted control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalDeleted;

        /// <summary>
        /// lblDeletedUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDeletedUsers;

        /// <summary>
        /// lblDeletedGroups control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDeletedGroups;

        /// <summary>
        /// lblDeletedProjects control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDeletedProjects;

        /// <summary>
        /// lblDeletedTasks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDeletedTasks;

        /// <summary>
        /// lblResultCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblResultCount;

        /// <summary>
        /// lblFilterDesc control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFilterDesc;

        /// <summary>
        /// lblPageInfo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPageInfo;

        /// <summary>
        /// btnPrevPage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPrevPage;

        /// <summary>
        /// btnNextPage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnNextPage;

        /// <summary>
        /// rptDeletedRecords control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptDeletedRecords;

        /// <summary>
        /// pnlEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        /// <summary>
        /// hdnModalEntityType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnModalEntityType;

        /// <summary>
        /// hdnModalEntityId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnModalEntityId;

        /// <summary>
        /// hdnModalEntityName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnModalEntityName;

        /// <summary>
        /// hdnModalDeletedBy control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnModalDeletedBy;

        /// <summary>
        /// hdnModalDeletedAt control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnModalDeletedAt;

        /// <summary>
        /// hdnModalReason control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnModalReason;

        /// <summary>
        /// hdnModalParent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnModalParent;

        /// <summary>
        /// hdnModalDetails control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnModalDetails;

        /// <summary>
        /// hdnShowModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnShowModal;

        /// <summary>
        /// hdnCurrentPage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnCurrentPage;
    }
}
