//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.Admin
{


    public partial class Admin_GroupsManagement
    {

        /// <summary>
        /// rptGroups control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptGroups;

        /// <summary>
        /// ddlReportFilter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlReportFilter;

        /// <summary>
        /// btnExportReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnExportReport;

        protected global::System.Web.UI.WebControls.HiddenField hdnEditGroupId;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditGroupStatus;
        protected global::System.Web.UI.WebControls.Label lblEditMessage;
        protected global::System.Web.UI.WebControls.Button btnUpdateGroup;
    }
}
