//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.Admin
{
    public partial class Admin_TaskManagement
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label userintial;
        protected global::System.Web.UI.WebControls.Label userNameLabel;
        protected global::System.Web.UI.WebControls.Label userEmailLabel;
        protected global::System.Web.UI.WebControls.DropDownList ddlGroups;
        protected global::System.Web.UI.WebControls.DropDownList ddlAssignToUser;
        protected global::System.Web.UI.WebControls.TextBox txtTaskTitle;
        protected global::System.Web.UI.WebControls.TextBox txtTaskDescription;
        protected global::System.Web.UI.WebControls.TextBox txtPointsToCover;
        protected global::System.Web.UI.WebControls.TextBox txtDueDate;
        protected global::System.Web.UI.WebControls.Button btnAdminCreateTask;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Repeater rptAdminTasks;
        protected global::System.Web.UI.WebControls.Label lblNoTasks;
        protected global::System.Web.UI.WebControls.DropDownList ddlReportFilter;
        protected global::System.Web.UI.WebControls.LinkButton btnExportReport;
        protected global::System.Web.UI.WebControls.CheckBox chkColTaskTitle;
        protected global::System.Web.UI.WebControls.CheckBox chkColTaskDescription;
        protected global::System.Web.UI.WebControls.CheckBox chkColGroupName;
        protected global::System.Web.UI.WebControls.CheckBox chkColAssignedTo;
        protected global::System.Web.UI.WebControls.CheckBox chkColAssignedBy;
        protected global::System.Web.UI.WebControls.CheckBox chkColLevel;
        protected global::System.Web.UI.WebControls.CheckBox chkColDueDate;
        protected global::System.Web.UI.WebControls.CheckBox chkColStatus;

    }
}

