//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.Admin
{


    public partial class Admin_TechManagement
    {

        /// <summary>
        /// rptTechs control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptTechs;

        /// <summary>
        /// txtNewTech control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewTech;

        /// <summary>
        /// btnAddTech control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddTech;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.DropDownList ddlFaculty;
        protected global::System.Web.UI.WebControls.DropDownList ddlTech;
        protected global::System.Web.UI.WebControls.Button btnAssign;
        protected global::System.Web.UI.WebControls.Label lblAssignMessage;
        protected global::System.Web.UI.WebControls.Repeater rptFacultyTech;
        protected global::System.Web.UI.WebControls.HiddenField hdnEditTechId;
        protected global::System.Web.UI.WebControls.TextBox txtEditTechName;
        protected global::System.Web.UI.WebControls.Label lblEditMessage;
    }
}
