//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.Admin
{


    public partial class Admin_UserManagement
    {

        /// <summary>
        /// rptUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptUsers;

        protected global::System.Web.UI.WebControls.DropDownList ddlReportFilter;
        protected global::System.Web.UI.WebControls.LinkButton btnExportReport;

        /// <summary>
        /// txtFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// txtPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        /// <summary>
        /// txtEnrollment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEnrollment;

        /// <summary>
        /// ddlRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRole;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// btnAddUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddUser;

        protected global::System.Web.UI.WebControls.HiddenField hdnEditUserId;
        protected global::System.Web.UI.WebControls.TextBox txtEditFullName;
        protected global::System.Web.UI.WebControls.TextBox txtEditEmail;
        protected global::System.Web.UI.WebControls.TextBox txtEditEnrollment;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditRole;
        protected global::System.Web.UI.WebControls.Label lblEditMessage;
        protected global::System.Web.UI.WebControls.Button btnUpdateUser;
    }
}
