//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.Admin
{
    public partial class Mentor_TaskManagement
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.DropDownList ddlGroups;
        protected global::System.Web.UI.WebControls.TextBox txtTaskTitle;
        protected global::System.Web.UI.WebControls.TextBox txtTaskDescription;
        protected global::System.Web.UI.WebControls.TextBox txtDueDate;
        protected global::System.Web.UI.WebControls.Button btnCreateTask;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterGroup;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;
        protected global::System.Web.UI.WebControls.Repeater rptMentorTasks;
        protected global::System.Web.UI.WebControls.Label lblNoTasks;
        protected global::System.Web.UI.WebControls.Label lblModalTitle;
        protected global::System.Web.UI.WebControls.Label lblModalGroup;
        protected global::System.Web.UI.WebControls.Label lblModalLeader;
        protected global::System.Web.UI.WebControls.Label lblModalStatus;
        protected global::System.Web.UI.WebControls.Label lblModalDescription;
        protected global::System.Web.UI.WebControls.Panel pnlReportContent;
        protected global::System.Web.UI.WebControls.Label lblModalReportText;
        protected global::System.Web.UI.WebControls.Label lblModalReportDate;
        protected global::System.Web.UI.WebControls.Panel pnlNoReport;
    }
}
