//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.Faculty.Details
{


    public partial class Group_Details
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label lblMessage;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DetailsContainer;
        
        protected global::System.Web.UI.WebControls.Literal litGroupName;
        
        protected global::System.Web.UI.WebControls.Literal litLeaderName;
        
        protected global::System.Web.UI.WebControls.Literal litTechnology;
        
        protected global::System.Web.UI.WebControls.Literal litStatus;
        
        protected global::System.Web.UI.WebControls.Repeater rptMembers;
    }
}
