//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.Faculty.Details
{
    public partial class Project_Details
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DetailsContainer;
        protected global::System.Web.UI.WebControls.Literal litProjectTitle;
        protected global::System.Web.UI.WebControls.Literal litGroupName;
        protected global::System.Web.UI.WebControls.Literal litProjectType;
        protected global::System.Web.UI.WebControls.Literal litStatus;
        protected global::System.Web.UI.WebControls.Literal litSubmittedAt;
        protected global::System.Web.UI.WebControls.Literal litFunctionality;
        protected global::System.Web.UI.WebControls.Repeater rptKeywords;
        protected global::System.Web.UI.WebControls.Button btnApprove;
        protected global::System.Web.UI.WebControls.Button btnReject;
    }
}
