//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.User
{
    public partial class Profile
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl avatarInitials;
        protected global::System.Web.UI.WebControls.PlaceHolder phStats;
        protected global::System.Web.UI.WebControls.Label lblDisplayName;
        protected global::System.Web.UI.WebControls.Label lblRoleBadge;
        protected global::System.Web.UI.WebControls.Label lblProjectsCount;
        protected global::System.Web.UI.WebControls.Label lblGroupsCount;
        protected global::System.Web.UI.WebControls.TextBox txtFullName;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtEnrollment;
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.LinkButton btnSave;
    }
}
