//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.Faculty
{
    public partial class ReviewAppeal
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.LinkButton btnBack;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        
        protected global::System.Web.UI.WebControls.Label lblTaskTitle;
        protected global::System.Web.UI.WebControls.Label lblGroupName;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Label lblTaskDescription;
        protected global::System.Web.UI.WebControls.Label lblRequirements;
        
        protected global::System.Web.UI.WebControls.Panel pnlAppeal;
        protected global::System.Web.UI.WebControls.Label lblReason;
        protected global::System.Web.UI.WebControls.Label lblChangesMade;
        protected global::System.Web.UI.WebControls.Label lblExplanation;
        protected global::System.Web.UI.WebControls.Label lblIsCompleted;
        protected global::System.Web.UI.WebControls.Label lblCreatedAt;
        
        protected global::System.Web.UI.WebControls.Panel pnlNoAppeal;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.TextBox txtFeedback;
        protected global::System.Web.UI.WebControls.Button btnSubmitDecision;
    }
}
