//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.Faculty
{
    public partial class TaskManagement
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.DropDownList ddlGroups;
        protected global::System.Web.UI.WebControls.DropDownList ddlAssignee;
        protected global::System.Web.UI.WebControls.TextBox txtTaskTitle;
        protected global::System.Web.UI.WebControls.TextBox txtTaskDescription;
        protected global::System.Web.UI.WebControls.TextBox txtPointsToCover;
        protected global::System.Web.UI.WebControls.TextBox txtDueDate;
        protected global::System.Web.UI.WebControls.Button btnCreateTask;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterGroup;
        protected global::System.Web.UI.WebControls.Repeater rptTasks;
        protected global::System.Web.UI.WebControls.Label lblNoTasks;
        protected global::System.Web.UI.WebControls.DropDownList ddlReportFilter;
        protected global::System.Web.UI.WebControls.LinkButton btnExportReport;
        protected global::System.Web.UI.WebControls.CheckBox chkColTaskTitle;
        protected global::System.Web.UI.WebControls.CheckBox chkColTaskDescription;
        protected global::System.Web.UI.WebControls.CheckBox chkColGroupName;
        protected global::System.Web.UI.WebControls.CheckBox chkColAssignedTo;
        protected global::System.Web.UI.WebControls.CheckBox chkColDueDate;
        protected global::System.Web.UI.WebControls.CheckBox chkColStatus;

    }
}

