//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Board.Faculty
{
    public partial class TaskDetails
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblTaskTitle;
        protected global::System.Web.UI.WebControls.Label lblGroupName;
        protected global::System.Web.UI.WebControls.Label lblAssignedTo;
        protected global::System.Web.UI.WebControls.Label lblStudentRole;
        protected global::System.Web.UI.WebControls.Label lblAssignedBy;
        protected global::System.Web.UI.WebControls.Label lblDueDate;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Label lblDescription;
        protected global::System.Web.UI.WebControls.Label lblPointsToCover;
        protected global::System.Web.UI.WebControls.Label lblReportText;
        protected global::System.Web.UI.WebControls.Label lblReportSubmittedAt;

        // Appeal Controls
        protected global::System.Web.UI.WebControls.Panel pnlAppealSection;
        protected global::System.Web.UI.WebControls.Label lblAppealReason;
        protected global::System.Web.UI.WebControls.Label lblAppealStatus;
        protected global::System.Web.UI.WebControls.Label lblAppealCreatedAt;
        protected global::System.Web.UI.WebControls.Label lblReviewerName;
        protected global::System.Web.UI.WebControls.Label lblReviewerRemarks;

        // Actions
        protected global::System.Web.UI.WebControls.TextBox txtRemarks;
        protected global::System.Web.UI.WebControls.Button btnMarkCompleted;
        protected global::System.Web.UI.WebControls.Button btnRejectCompletion;
        protected global::System.Web.UI.WebControls.Button btnAcceptAppeal;
        protected global::System.Web.UI.WebControls.Button btnRejectAppeal;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
